name = "requestbin"
main = "src/index.ts"
account_id = "4327cb5c94e7ca3e5c5e1b3227722738"
compatibility_date = "2023-10-25"
route = "requestbin.xela.tech/*"

[[d1_databases]]
binding = "DB"
database_name = "requestbin-db"
database_id = "9cfafee9-d5ca-4cfb-b2d4-e71fc82e9ed1"
preview_database_id = "ec172618-ea70-417f-b5ba-57530ddacc5c"
