name = "requestbin"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "4327cb5c94e7ca3e5c5e1b3227722738"
compatibility_date = "2022-07-23"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.dev]
name = "requestbin-dev"
workers_dev = true
kv_namespaces = [
    { binding = "BINS", id = "a7ef2bc7397244d094f68c58aed88aeb", preview_id = "a7ef2bc7397244d094f68c58aed88aeb" }
]

[env.prod]
kv_namespaces = [
    { binding = "BINS", id = "ac7af24308fe4ba39dda19739c389c24" }
]
